apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |+
    [[outputs.influxdb_v2]]
      urls = ["http://influxdb:8086"]
      token = "X-YJF-JEIHXPNBiebdnG9mXVVflbh3Xito-QBMCiKAjrNvVd1A9a-v_m-k3j-9pPTr67W5hjqQc6gN1r0nA7hw=="
      organization = "kubermates"
      bucket = "monitoring"

    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
